forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.index, name='index'),
    path('newpost/', views.new_post, name='new_post'),
    path('<slug:post>/', views.post_single, name='post_single'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('penggunaan-masker/', views.penggunaan_masker, name='masker'),
    path('tips-trick/', views.tips_trick, name='tips-trick')
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.logging_in, name='logging_in'),
    path('logout/', views.logging_out, name='logging_out')
]

news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.tambahKomentar, name='news'),
    # path('Detail/', views.jumlahkasus, name='jumlahkasus'),
    path('detail', views.kasus, name='kasus'),

]

tk1_ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('donasi/', include("donasi.urls")),
    path('forum/', include("forum.urls")),
    path('account/', include("login.urls")),
    path('news/', include("news.urls")),
]

home/models.py
from django.db import models

# Create your models here.
class TipsTrick(models.Model):
    name = models.CharField(max_length=50, blank=False)
    message = models.CharField(max_length=300, blank=False)

home/forms.py
from django import forms

class TipsTrickForm(forms.Form):
    name = forms.CharField(label="Nama", widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Masukkan Nama Anda',
        'required': True,
    }))

    message = forms.CharField(label="Tips & Trick", widget=forms.Textarea(attrs={
        'rows': 6,
        'style': 'resize:none;',
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Tulis Tips & Trick versi kamu!',
        'required': True,
    }))

home/views.py
from django.shortcuts import render
from .forms import TipsTrickForm
from .models import TipsTrick

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

def penggunaan_masker(request):
    return render(request,'home/penggunaan-masker.html')

def tips_trick(request):
    if request.method == 'POST':
        tips_form = TipsTrickForm(request.POST)
        if tips_form.is_valid():
            tips_trick = TipsTrick()
            tips_trick.name = tips_form.cleaned_data['name']
            tips_trick.message = tips_form.cleaned_data['message']
            tips_trick.save()
    form = TipsTrickForm()
    response = {'form':form}
    response['data'] = TipsTrick.objects.all()
    return render(request, 'home/tips-trick.html',response)

home/templates/home/base.html
<!DOCTYPE html>
<html>
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/yourcode.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js " integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN " crossorigin="anonymous "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js " integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q " crossorigin="anonymous "></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js " integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl " crossorigin="anonymous "></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> {% block meta %} {% endblock meta %}
</head>

<body>
    <nav class="navbar fixed-top navbar navbar-expand-lg navbar-dark" style="background-color:#62959A">
        <a href="#" class="navbar-brand">
            <!-- Logo Image -->
            <img src="{% static 'home/images/virus-logo.png' %}" width="45" alt="" class="d-inline-block align-middle mr-2">
            <!-- Logo Text -->
            <span class="text-uppercase font-weight-bold">COVID<span style="color:#F0AD4E">-19</span></span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" style="justify-content: center;" id="navbarNavDropdown">
            <ul class="navbar-nav" style="margin: auto;">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home:index' %}">HOME <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:tips-trick' %}">TIPS & TRICKS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:news' %}">NEWS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">MAP</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:index' %}">DISCUSSION</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}#contact">CONTACT</a>
                </li>
            </ul>
            <div class="navbar-nav">
                {% if not request.user.is_authenticated %}
                <a href="{% url 'login:logging_in' %}" class="nav-item nav-link button-login">LOGIN</a>
                <a href="{% url 'login:register' %}" class="nav-item nav-link button-signup">SIGN UP</a> {% else %}
                <a href="{% url 'login:logging_out' %}" class="nav-item nav-link button-signup">LOGOUT</a> {% endif %}
            </div>
        </div>
    </nav>

    {% block content %} {% endblock %}
    <!-- Footer -->
    <!-- <section id="footer">
        <div class="footer container">
            <p></p>
        </div>
    </section> -->
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3" style="background-color: #62959A;">Copyright © 2020 tk-ppw-06. All rights reserved</div>
    <!-- Copyright -->
    <!-- End Footer -->

</body>

</html>

home/templates/home/index.html
{% extends 'home/base.html' %} {% load static %} {% block meta %}
<title>Test</title>
<!-- Home Section  -->
<section id="home">
    <!-- Columns are always 50% wide, on mobile and desktop -->
    <div class="home-row">
        <div class="col-left">
            <h1 class="lindungi">LINDUNGI DIRI KITA</h1>
            <h1 class="lawan">LAWAN CORONA</h1>
            <p class="ayo-bantu">Ayo bantu keluarga kita dengan <br>berdonasi sekarang!</p>
            <a href="#" type="button" class="cta">DONASI SEKARANG</a>
        </div>
        <div class="col-right">
            <img src="{% static 'home/images/home.jpg' %}" class="image foto-home" />
        </div>
    </div>
</section>
<!-- End Home Section  -->

<!-- Tips & Trick Section  -->
<Section id="tips-trick">
    <div class="tips-row">
        <div class="tips-col-left">
            <h1 class="gunakan-masker">GUNAKAN MASKER</h1>
            <p class="coba-guna">Menggunakan masker melindungi orang di sekitarmu.</p>
            <p>
                <a href="{% url 'home:masker' %}" type="button" class="masker" style="background-color: #007D91; color: white;  text-decoration: none;">PENGGUNAAN MASKER YANG TEPAT</a>
                <a href="{% url 'home:tips-trick' %}" type="button" class="masker" style=" text-decoration: none;color: white; ">TIPS & TRICK PENCEGAHAN COVID-19</a>
            </p>
        </div>
        <div class="tips-col-right">
            <img src="{% static 'home/images/masker.png' %}" class="image foto-masker" />
        </div>
    </div>

</Section>
<!-- End Tips & Trick Section -->

<!-- Donasi Section -->
<Section id="donasi">
    <div class="div-donasi">
        <h1 class="bantu">
            <span style="color:#007D91;">BANTU </span>KELUARGA KITA DENGAN <span style="color:#007D91;">BERDONASI</span>
        </h1>
        <h1 class="bantu" style="color:#007D91;">SEKARANG</h1>
    </div>
    <div class="karusel">
        <div id=" carouselExampleIndicators " class="carousel slide " data-ride="carousel ">
            <ol class="carousel-indicators ">
                <li data-target="#carouselExampleIndicators " data-slide-to="0 " class="active "></li>
                <li data-target="#carouselExampleIndicators " data-slide-to="1 "></li>
                <li data-target="#carouselExampleIndicators " data-slide-to="2 "></li>
            </ol>
            <div class="carousel-inner ">
                <div class="carousel-item active ">
                    <img class="d-block w-100 " src="{% static 'home/images/v1.jpg' %} " class="image " alt="First slide ">
                </div>
                <div class="carousel-item ">
                    <img class="d-block w-100 " src="{% static 'home/images/v2.jpg' %} " class="image " alt="Second slide ">
                </div>
                <div class="carousel-item ">
                    <img class="d-block w-100 " src="{% static 'home/images/v3.jpg' %} " class="image " alt="Third slide ">
                </div>
            </div>
            <a class="carousel-control-prev " href="#carouselExampleIndicators " role="button " data-slide="prev ">
                <span class="carousel-control-prev-icon " aria-hidden="true "></span>
                <span class="sr-only ">Previous</span>
            </a>
            <a class="carousel-control-next " href="#carouselExampleIndicators " role="button " data-slide="next ">
                <span class="carousel-control-next-icon " aria-hidden="true "></span>
                <span class="sr-only ">Next</span>
            </a>
        </div>
    </div>
    <div class="tombol">
        <a href="#" type="button" class="tombol-karusel">DONASI SEKARANG</a>
    </div>

</Section>
<!-- End Donasi Section -->

<!-- Contact Info Section -->
<section id="contact">
    <div class="contact container kontak">
        <div>
            <h1 class="section-title">CONTACT <span>INFO</span></h1>
        </div>
        <div class="contact-items">
            <div class="contact-item">
                <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/phone.png" /></div>
                <div class="contact-info">
                    <h1>Phone</h1>
                    <h2>+1 234 123 1234</h2>
                    <h2>+1 234 123 1234</h2>
                </div>
            </div>
            <div class="contact-item">
                <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/new-post.png" /></div>
                <div class="contact-info">
                    <h1>Email</h1>
                    <h2>info@gmail.com</h2>
                    <h2>abcd@gmail.com</h2>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>

<!-- End Contact Info Section -->
<section id="footer">
    <div class="footer container">
        <h2>Follow Us</h2>
        <div class="social-icon">
            <div class="social-item">
                <a href="#"><img src="{% static 'home/images/instagram.png' %}" class="image" /></a>
            </div>
            <div class="social-item">
                <a href="#"><img src="{% static 'home/images/line.png' %}" class="image" /></a>
            </div>
            <div class="social-item">
                <a href="#"><img src="{% static 'home/images/twitter.png' %}" class="image" /></a>
            </div>
            <div class="social-item">
                <a href="#"><img src="{% static 'home/images/linkedin.png' %}" class="image" /></a>
            </div>
        </div>
    </div>
</section>

{% endblock %}

home/templates/home/penggunaan-masker.html
{% extends 'home/base.html' %} {% load static %} {% block meta %}
<title>Tips & Trick</title>
<style>
    * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
    }
    
    .section-title-judul {
        background: #F0AD4E;
        border-radius: 9px;
        text-align: center;
        color: white;
        padding: 3px 8px;
        line-height: 50px;
        margin-bottom: 10px;
        margin-top: 30px;
        font-size: 24px;
    }
    
    .image {
        height: auto;
        width: 200px;
        padding-bottom: 50px;
    }
    
    .hobby-container {
        flex-direction: column;
        text-align: center;
        max-width: 100%;
        margin: 0 auto;
        padding: 100px 0;
        background-color: #ffffff;
    }
    
    .hobby-top {
        max-width: 300px;
        margin: 0 auto;
    }
    
    .hobby-bottom {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-wrap: wrap;
        margin-top: 50px;
    }
    
    .hobby-item {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        padding: 30px;
        border-radius: 10px;
        /* margin: 10px 5%; */
        position: relative;
        z-index: 1;
        overflow: hidden;
    }
    
    .name {
        display: flex;
        flex-direction: column;
        margin-left: 30px;
        text-align: center;
    }
    /* .hobby-bottom .icon {
        height: 20px;
        width: 20px;
        margin-bottom: 20px;
    } */
    
    .hobby-item h2 {
        font-size: 1.5rem;
        margin-bottom: 10px;
        text-transform: uppercase;
    }
    
    .hobby-item p {
        color: black;
        text-align: center;
    }
    /* @media only screen and (min-width: 768px) {
        .section-title-judul {
            font-size: 16px;
        }
    } */
</style>

<section id="hobby">
    <div class="hobby-container">
        <div class="hobby-top">
            <h1 class="section-title-judul">KAPAN</h1>
        </div>
        <div class="hobby-bottom">
            <div class="hobby-item">
                <img src="{% static 'home/images/masker1.jpg' %}" class="image" />
                <div class="name">
                    <h2>Batuk / Bersin</h2>
                </div>
            </div>
            <div class="hobby-item">
                <img src="{% static 'home/images/masker2.jpg' %}" class="image" />
                <div class="name">
                    <h2>Merawat Pasian COVID-19</h2>
                </div>
            </div>
            <div class="hobby-item">
                <img src="{% static 'home/images/masker3.jpg' %}" class="image" />
                <div class="name">
                    <h2>Buang Masker</h2>
                </div>
            </div>
        </div>
        <div class="hobby-top">
            <h1 class="section-title-judul">BAGAIMANA</h1>
        </div>
        <div class="hobby-bottom">
            <div class="hobby-item">
                <img src="{% static 'home/images/cuci-tangan.jpg' %}" class="image" />
                <div class="name">
                    <h2>Membersihkan Tangan</h2>
                </div>
            </div>
            <div class="hobby-item">
                <img src="{% static 'home/images/cuci-tangan2.jpg' %}" class="image" />
                <div class="name">
                    <h2>Menutup Hidung & Mulut</h2>
                </div>
            </div>
            <div class="hobby-item">
                <img src="{% static 'home/images/cuci-tangan3.jpg' %}" class="image" />
                <div class="name">
                    <h2>Melepas Masker dari Belakang</h2>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

home/templates/home/tips-trick.html
{% extends 'home/base.html' %} {% load static %} {% block meta %}
<style>
    #tips-trick {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        padding-top: 50px;
        padding-bottom: 50px;
    }
    
    .card {
        min-width: 200px;
        max-width: 400px;
        border: none;
        display: inline-block;
        padding: 10px 25px;
        /* cursor: pointer; */
        border-radius: 36px;
        box-shadow: 2px 6px 20px rgba(0, 0, 0, 0.25);
    }
    
    .col-mw {
        min-width: 220px;
        max-width: 430px;
    }
    
    .m-auto {
        margin: auto 0;
    }
    
    .row {
        margin: 0;
    }
    
    .card>p {
        font-size: 1rem;
        font-weight: 400;
    }
    
    .card>h2 {
        font-size: 1.2rem;
        font-weight: 700;
        color: white;
    }
    
    .mb-2 {
        margin-top: 1rem;
        background-color: #16636D;
        color: white;
    }
    
    .button {
        margin: 0;
    }
    
    .mr-6 {
        margin-right: 3rem;
    }
    
    .tombol {
        background: #F0AD4E;
        border-radius: 9px;
        text-align: center;
        color: white;
        padding: 3px 10px;
    }
    
    .tips {
        background: #F0AD4E;
        border-radius: 9px;
        text-align: center;
        color: white;
        padding: 3px 8px;
        line-height: 50px;
        margin-bottom: 30px;
        margin-top: 100px;
    }
    
    p {
        color: white;
    }
    
    @media (max-width: 767.98px) {
        #header h1 {
            font-size: 5rem;
        }
    }
    
    @media (max-width: 750px) {
        #header h1 {
            font-size: 4rem;
        }
    }
    
    @media (max-width: 640px) {
        #header h1 {
            padding-top: 1rem;
            font-size: 3.5rem;
        }
    }
</style>

<section id="tips-trick">
    <div class="row" style="margin-left: 20px;">
        <div class="col-md">
            <div class=" col-mw ">
                <h3 class="tips ">Apa Tips & Trick Kamu?</h3>
                <form action='' method="POST ">
                    {% csrf_token %} {{ form.name.label_tag }} {{ form.name }}
                    <br> {{ form.message.label_tag }} {{ form.message }}
                    <br>
                    <input type="submit " class="tombol " value="Submit ">
                </form>
            </div>
        </div>
        <div class="col-md flex-row " style="max-height: 300px;overflow-y: scroll; ">
            {% for object in data %}
            <div class="card b-green mb-2 w-100 ">
                <h2>
                    {{ object.name }}
                </h2>
                <p>
                    {{ object.message }}
                </p>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}