forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.index, name='index'),
    path('newpost/', views.new_post, name='new_post'),
    path('<slug:post>/', views.post_single, name='post_single'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('penggunaan-masker/', views.penggunaan_masker, name='masker'),
    path('tips-trick/', views.tips_trick, name='tips-trick')
]

tk1_ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('donasi/', include("donasi.urls")),
    path('forum/', include("forum.urls")),
    path('account/', include("login.urls")),
    path('news/', include("news.urls")),
]

forum/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey

class Post(models.Model):

    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250, unique=True)
    excerpt = models.TextField(null=True)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    author = models.CharField(max_length=50)
    content = models.TextField()
    status = models.CharField(max_length=10, choices=options, default='published')
    objects = models.Manager()  # default manager
    newmanager = NewManager()  # custom manager

    def get_absolute_url(self):
        return reverse('forum:post_single', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(MPTTModel):

    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    email = models.EmailField()
    content = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['publish']

    def __str__(self):
        return self.name

forum/forms.py
from django import forms
from .models import Comment, Post
from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        fields = ('name', 'parent', 'email', 'content')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Nama'}),
            'email': forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'E-mail'}),
            'content': forms.Textarea(attrs={'class': 'form-control mb-3', 'placeholder': 'Konten'}),
        }

        labels = {
            'name': 'Nama',
            'email': "E-mail",
            'content': 'Konten',
        }

    def save(self, *args, **kwargs):
        Comment.objects.rebuild()
        return super(NewCommentForm, self).save(*args, **kwargs)

class PostForm(forms.ModelForm):
    title = forms.CharField(label="Judul",
                           widget=forms.TextInput(
                               attrs={
                                   "placeholder": "Judul",
                                   "class": "form-control",
                               }
                           )
                           )
    author = forms.CharField(label="Nama",
                           widget=forms.TextInput(
                               attrs={
                                   "placeholder": "Nama",
                                   "class": "form-control",
                               }
                           )
                           )
    excerpt = forms.CharField(label="Kutipan",
                           widget=forms.TextInput(
                               attrs={
                                   "placeholder": "Kutipan",
                                   "class": "form-control",
                               }
                           )
                           )
    content = forms.CharField(label="Konten",
                           widget=forms.Textarea(
                               attrs={
                                   "placeholder": "Konten",
                                   "class": "form-control",
                               }
                           )
                           )
    class Meta:
        model = Post
        fields = [
            'title',
            'author',
            'excerpt',
            'content',
        ]

forum/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Post, Comment
from .forms import NewCommentForm, PostForm
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.defaultfilters import slugify

def index(request):
    all_posts = Post.newmanager.all()
    return render(request, 'index.html', {'posts': all_posts})

def post_single(request, post):

    post = get_object_or_404(Post, slug=post, status='published')

    allcomments = post.comments.filter(status=True)
    page = request.GET.get('page', 1)

    paginator = Paginator(allcomments, 10)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    user_comment = None

    if request.method == 'POST':
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.save()
            return HttpResponseRedirect('/forum/' + post.slug)
    else:
        comment_form = NewCommentForm()
    return render(request, 'single.html', {'post': post, 'comments':  user_comment, 'comments': comments, 'comment_form': comment_form, 'allcomments': allcomments, })

def new_post(request):
    form = PostForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        post = form.save(commit=False)
        post.slug = slugify(post.title)
        post.save()
        return HttpResponseRedirect('/forum/')
    context = {
        'form': form
    }
    return render(request, 'newpost.html', context)

forum/templates/index.html
{% extends 'home/base.html' %}
{% block content %}
<h1 style="text-align: center; margin-top: 100px;">Forum Diskusi</h1>
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          {% for post in posts %}
          <div class="col-md-4">
            <a class="text-dark" href="{{post.get_absolute_url}}">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="h4"">{{post.title|truncatechars:50}}</p>
                  <p class="lead card-text">{{post.excerpt|truncatechars:50}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">{{post.publish|date:'d/m/Y'}} - {{ post.author }}</small>
                  </div>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row justify-content-center">
          <a class="btn btn-dark" href="newpost" role="button">Buat post baru</a>
      </div>
    </div>
<br>
    {% endblock %}

forum/templates/newpost.html
{% extends 'home/base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Buat post baru</b></h2>
        <hr class="mt-0 mb-4">
        <form method='POST'>
            {% csrf_token %}
            {{ form.as_p }}
            <br>
           <button type="submit" class="btn btn-dark">Submit</button>
           <a class="btn btn-dark" href="../">Kembali</a>
        </form>
        <br>
      </div>
    </div>
  </div>
<br>

{% endblock %}

forum/templates/single.html
{% extends 'home/base.html' %}
{% load humanize %}

{% block content %}

<style>
  @media screen and (min-width: 600px) {
    .children form {
      margin-left: -48px;
      /* will touch very left side */
    }

    .children .children form {
      margin-left: -96px;
      /* will touch very left side */
    }
  }
</style>

<br>
<br>

<div class="container">
  <div class="row justify-content-md-center pt-5">

    <div class="col-md-7">
      <p class="h2">{{post.title}}</p>
    </div>
    <div class="col-md-7">
      <p class="text-justify" style="font-size: 20px;">{{post.content|safe}}</p>
    </div>
    <div class="col-md-7">

      {% with allcomments.count as total_comments %}
      <h5 class="lead">
        {{ total_comments }} komentar
      </h5>
      {% endwith %}

      {% load mptt_tags %}

      <div>
        {% recursetree comments %}
        <div id="{{ node.id }}" class="my-2 p-2 rounded">
          <div class="d-flex justify-content-between"><b>{{ node.name }}</b><div></div>{{ node.publish|naturaltime }}</div>
          <div>{{ node.content }}</div>
          <hr>
          {% if node.level < 3 %}
          <button class="btn btn-light" onclick="myFunction({{ node.id }})">Balas</button>
          {% endif %}
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5">
          {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>

      <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if comments.has_other_pages %}
          <ul class="pagination">
            {% if comments.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}"><</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#"><</a></li>
            {% endif %}
            {% for num in comments.paginator.page_range %}
            {% if comments.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if comments.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">></a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">></a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </div>

      <button onclick="thatFunction()" class="btn btn-dark">Buat komentar baru</button>

      <div id="thatDIV" style="display:none;">
        <form id="myForm" method="post">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-dark" >Submit</button>
        </form>
      </div>

    </div>
  </div>
</div>
<br>
<script>
  function thatFunction() {
    var x = document.getElementById("thatDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
  }  

  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      '<form id="newForm" class="form-insert py-2" method="post"> \
                <label for="id_name">Nama:</label> \
                <input type="text" name="name" class="col-sm-12" maxlength="50" required="" id="id_name" placeholder="Nama">\
                <select name="parent" class="d-none" id="id_parentt"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                <label for="id_email">E-mail:</label> \
                <input type="text" name="email" class="col-sm-12" maxlength="254" required="" id="id_email" placeholder="E-mail"> \
                <label for="id_content">Konten:</label> \
                <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content" placeholder="Konten"></textarea> \
                {% csrf_token %} \
                <br> \
                <button type="submit" class="btn btn-dark">Submit</button> <button type="button" class="btn btn-dark" onclick="formExit()"">Close</button> \
              </form>');

    //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
  }

  $('#myForm').trigger("reset");
</script>

{% endblock %}