forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.index, name='index'),
    path('newpost/', views.new_post, name='new_post'),
    path('<slug:post>/', views.post_single, name='post_single'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('penggunaan-masker/', views.penggunaan_masker, name='masker'),
    path('tips-trick/', views.tips_trick, name='tips-trick')
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.logging_in, name='logging_in'),
    path('logout/', views.logging_out, name='logging_out')
]

news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.tambahKomentar, name='news'),
    # path('Detail/', views.jumlahkasus, name='jumlahkasus'),
    path('detail', views.kasus, name='kasus'),

]

tk1_ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('donasi/', include("donasi.urls")),
    path('forum/', include("forum.urls")),
    path('account/', include("login.urls")),
    path('news/', include("news.urls")),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class komentar(models.Model):
    komentar = models.CharField(blank=False, max_length= 300)

    def __str__(self):
        return self.komentar

news/forms.py
from django import forms

class komentarForm(forms.Form):
    komentar = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control form-control-lg',
        # 'placeholder' : 'Berikan komentarmu terkait berita tersebut!',
        'type' : 'text',
        'required' : False,
    }))

class updateKasusForm(forms.Form):
    confirm_case = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control ',
        # 'placeholder' : 
        'type' : 'text',
        'required' : False,
    }))
    active_case = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control ',
        # 'placeholder' : 
        'type' : 'text',
        'required' : False,
    }))
    cured_case = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control ',
        # 'placeholder' : 
        'type' : 'text',
        'required' : False,
    }))
    region = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control ',
        # 'placeholder' : 
        'type' : 'text',
        'required' : False,
    }))

news/views.py
from django.shortcuts import render, redirect
from .forms import komentarForm, updateKasusForm
from .models import komentar

# Create your views here.
# def news(request):
#     return render(request, 'news.html')

# def jumlahkasus(request):
#     return render(request, 'jumlahkasus.html')

def tambahKomentar(request):
    if request.method == 'POST':
        form = komentarForm(request.POST)
        if form.is_valid():
            inpMasuk = komentar()
            inpMasuk.komentar = form.cleaned_data['komentar']
            inpMasuk.save()
        return redirect("/news")

    else:
            inpMasuk = komentar.objects.all()
            form = komentarForm()
            response = {'inpMasuk':inpMasuk, 'form': form}
            return render(request, 'news.html', response)

def kasus(request):
    if request.method == 'POST':
        form2 = updateKasusForm(request.POST)
        return redirect("/detail")
    else:
        form2 = updateKasusForm()
        response = {'form2' : form2}
        return render(request, 'jumlahkasus.html', response)

news/templates/jumlahkasus.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
        <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/yourcode.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
    </head>
    
    <body class="bg-color-kasus">
        <nav class="navbar fixed-top navbar navbar-expand-lg navbar-dark" style="background-color:#62959A;">
            <a href="#" class="navbar-brand">
                <!-- Logo Image -->
                <img src="{% static 'home/images/virus-logo.png' %}" width="45" alt="" class="d-inline-block align-middle mr-2">
                <!-- Logo Text -->
                <span class="text-uppercase font-weight-bold">COVID<span style="color:#F0AD4E">-19</span></span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" style="justify-content: center;" id="navbarNavDropdown">
                <ul class="navbar-nav" style="margin: auto;">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home:index' %}">HOME <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:tips-trick' %}">TIPS & TRICKS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:index' %}">NEWS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">MAP</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'forum:index' %}">DISCUSSION</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:index' %}#contact">CONTACT</a>
                    </li>
                </ul>
                <div class="navbar-nav">
                    {% if not request.user.is_authenticated %}
                        <a href="{% url 'login:logging_in' %}" class="nav-item nav-link button-login">LOGIN</a>
                        <a href="{% url 'login:register' %}" class="nav-item nav-link button-signup">SIGN UP</a>
                    {% else %}
                        <a href="{% url 'login:logging_out' %}" class="nav-item nav-link button-signup">LOGOUT</a>
                    {% endif %}
                </div>
            </div>
        </nav>





        
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3 style="text-align: center; margin-top: 100px;">JAKARTA</h3>
                </div>
            </div>
        </div>
        <div id="jakarta" class="d-flex align-items-center justify-content-around">
            <div class="p-2"><b>Confirmed Case <p>1029820</p></b></div>
            <div class="p-2"><b>Active Case <p>0013</p></b></div>
            <div class="p-2"><b>Cured Case <p>3123010</p></b></div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3 style="text-align: center;">BOGOR</h3>
                </div>
            </div>
        </div>
        <div id="bogor" class="d-flex align-items-center justify-content-around">
            <div class="p-2"><b>Confirmed Case <p>0000000</p></b></div>
            <div class="p-2"><b>Active Case <p>0000</p></b></div>
            <div class="p-2"><b>Cured Case <p>000000</p></b></div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3 style="text-align: center;">DEPOK</h3>
                </div>
            </div>
        </div>
        <div id="depok" class="d-flex align-items-center justify-content-around">
            <div class="p-2"><b>Confirmed Case <p>000000</p></b></div>
            <div class="p-2"><b>Active Case <p>0000</p></b></div>
            <div class="p-2"><b>Cured Case <p>000000</p></b></div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3 style="text-align: center;">TANGERANG</h3>
                </div>
            </div>
        </div>
        <div id="tangerang" class="d-flex align-items-center justify-content-around">
            <div class="p-2"><b>Confirmed Case <p>14564</p></b></div>
            <div class="p-2"><b>Active Case <p>1231</p></b></div>
            <div class="p-2"><b>Cured Case <p>10000</p></b></div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3 style="text-align: center;">BEKASI</h3>
                </div>
            </div>
        </div>
        <div id="bekasi" class="d-flex align-items-center justify-content-around">
            <div class="p-2"><b>Confirmed Case <p>14564</p></b></div>
            <div class="p-2"><b>Active Case <p>1231</p></b></div>
            <div class="p-2"><b>Cured Case <p>10000</p></b></div>
        </div>
        <div class="col-6">
            <form action='' method="POST">
                {% csrf_token %}
                {{ form2.as_p }}
            </form>
            <p style="margin-bottom: 40px;">*Fitur update dan tambah hanya dapat dilakukan oleh admin</p>  
        </div>
        <div class="container" style="margin-bottom: 50px;">
            <div class="row"> 
                <div class="col-3">
                    <div>
                        <input type="submit" class="btn btn-update" value="Update">
                    </div>
                </div>
                <div class="col-3">
                    <div>
                        <input type="submit" class="btn btn-tambah" value="Tambah">
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-copyright text-center py-3" style="background-color: #62959A;">Copyright © 2020 tk-ppw-06. All rights reserved</div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js " integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN " crossorigin="anonymous "></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js " integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q " crossorigin="anonymous "></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js " integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl " crossorigin="anonymous "></script>
    </body>
</html>

news/templates/news.html
<!DOCTYPE html>
<html>
    {% load static %} 
    <head>
        <meta charset="utf-8">
        <title>Update Berita</title>
        <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        
        
        <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
        <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/yourcode.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
    </head>
    
    
    <body>
        <nav class="navbar fixed-top navbar navbar-expand-lg navbar-dark" style="background-color:#62959A">
            <a href="#" class="navbar-brand">
                <!-- Logo Image -->
                <img src="{% static 'home/images/virus-logo.png' %}" width="45" alt="" class="d-inline-block align-middle mr-2">
                <!-- Logo Text -->
                <span class="text-uppercase font-weight-bold">COVID<span style="color:#F0AD4E">-19</span></span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" style="justify-content: center;" id="navbarNavDropdown">
                <ul class="navbar-nav" style="margin: auto;">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home:index' %}">HOME <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:tips-trick' %}">TIPS & TRICKS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'news:news' %}">NEWS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">MAP</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'forum:index' %}">DISCUSSION</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:index' %}#contact">CONTACT</a>
                    </li>
                </ul>
                <div class="navbar-nav">
                    {% if not request.user.is_authenticated %}
                        <a href="{% url 'login:logging_in' %}" class="nav-item nav-link button-login">LOGIN</a>
                        <a href="{% url 'login:register' %}" class="nav-item nav-link button-signup">SIGN UP</a>
                    {% else %}
                        <a href="{% url 'login:logging_out' %}" class="nav-item nav-link button-signup">LOGOUT</a>
                    {% endif %}
                </div>
            </div>
        </nav>





        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1 style="text-align: center; margin-top: 100px;">Peta sebaran COVID-19 <p>JABODETABEK</p></h1>
                    <img src="{% static 'petaSebaran.png' %}" class="img-fluid rounded" alt="Responsive image">
                    <a href="{% url 'news:kasus' %}"><button class="btn btn-atas"> <b>DETAILS </b></button>
                </a>
            
                    <hr class="hr-rounded">
                </div>
                <div class="col-12">
                    <h2 style="text-align: center;">Update Terkini Seputar <p>COVID-19</p></h2>
                </div>
                <div id="kotak1" class="col-12">
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="false">
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                            <div class="embed-responsive embed-responsive-4by3">
                                <iframe class="embed-responsive-item" src="https://www.kompas.com/tren/read/2020/10/08/084000965/update-terkini-vaksin-covid-19--dari-indonesia-hingga-dunia?page=all"></iframe>
                            </div>
                          </div>
                          <div class="carousel-item">
                            <div class="embed-responsive embed-responsive-4by3">
                                <iframe class="embed-responsive-item" src="https://www.liputan6.com/cek-fakta/read/4398920/informasi-hoaks-seputar-covid-19-virus-tidak-menyebar-ke-udara-hingga-konspirasi"></iframe>
                            </div>
                          </div>
                          <div class="carousel-item">
                            <div class="embed-responsive embed-responsive-4by3">
                                <iframe class="embed-responsive-item" src="https://republika.co.id/berita/qie2gy428/kemenkominfo-blokir-1759-hoaks-seputar-covid19-di-medsos"></iframe>
                            </div>
                          </div>
                          <div class="carousel-item">
                            <div class="embed-responsive embed-responsive-4by3">
                                <iframe class="embed-responsive-item" src="https://www.cnbcindonesia.com/tech/20201111063317-37-200901/kabar-baik-kabar-buruk-dari-vaksin-covid-19-simak-yah"></iframe>
                            </div>
                          </div>
                          <div class="carousel-item">
                            <div class="embed-responsive embed-responsive-4by3">
                                <iframe class="embed-responsive-item" src="https://nasional.kompas.com/read/2020/11/11/06380431/444348-kasus-covid-19-di-indonesia-dan-19-daerah-yang-jadi-zona-merah?page=all"></iframe>
                            </div>
                          </div>
                        </div>

                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                    </div>
                        </div>
    
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    
                    </div>
    
                </div>
                {% if not request.user.is_authenticated %}
                <div id="judulKomentar" class="col-5" style="margin-top: 40px; margin-left: 15px;">
                    <a class="effect effect-5" href="{% url 'login:logging_in' %}"><h4 style="color: white;">Login untuk menambahkan komentar</h4></a>
                </div>
                <div class="w-100"></div>
                {% else %}
                <div id="judulKomentar" class="col-5" style="margin-top: 40px; margin-left: 15px;">
                    <h4>Tuliskan komentarmu terkait berita COVID-19</h4>
                </div>
                <div class="w-100"></div>
                <div class="col-12">
                    <form action='' method="POST" style="margin-top: 20px;">
                        {% csrf_token %}
                        {{ form.komentar }}
                        <br>
                        <div style="margin-top: 20px;">
                            <input type="submit" id="button2" class="btn btn-primary"  value="Submit">
                        </div>
                    </form>
                </div>
                {% endif %}
                <div class="col-12" style="margin-top: 40px; margin-bottom: 50px;">
                    <h3><b>Komentar</b></h3>
                    <ul class="list-group">
                        {% for isi in inpMasuk %}
                        <li class="list-group-item">{{isi.komentar}}</li>
                        <div></div>
                        {% endfor %}
                    </ul>
                </div>

                
            </div>
        </div>
        

        <div class="footer-copyright text-center py-3" style="background-color: #62959A;">Copyright © 2020 tk-ppw-06. All rights reserved</div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js " integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN " crossorigin="anonymous "></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js " integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q " crossorigin="anonymous "></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js " integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl " crossorigin="anonymous "></script>
        
    </body>
    
</html>